In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({'col1' : [1,2,3,4,5],
              'col2' : [45,56,67,34,34],
              'col3': "sudhanshu kumar krish ineuron one".split()
     })

In [3]:
"sudhanshu kumar krish ineuron one".split()

['sudhanshu', 'kumar', 'krish', 'ineuron', 'one']

In [4]:
df

col1  col2       col3
0     1    45  sudhanshu
1     2    56      kumar
2     3    67      krish
3     4    34    ineuron
4     5    34        one

In [5]:
df['col4'] = df['col1']**2

In [6]:
df

col1  col2       col3  col4
0     1    45  sudhanshu     1
1     2    56      kumar     4
2     3    67      krish     9
3     4    34    ineuron    16
4     5    34        one    25

In [7]:
df['col5'] = df['col3'].str[0]

In [8]:
df

col1  col2       col3  col4 col5
0     1    45  sudhanshu     1    s
1     2    56      kumar     4    k
2     3    67      krish     9    k
3     4    34    ineuron    16    i
4     5    34        one    25    o

In [9]:
def test(a) :
    return a**2

In [10]:
df['col4_4']  = df['col1'].apply(test)

In [11]:
df

col1  col2       col3  col4 col5  col4_4
0     1    45  sudhanshu     1    s       1
1     2    56      kumar     4    k       4
2     3    67      krish     9    k       9
3     4    34    ineuron    16    i      16
4     5    34        one    25    o      25

In [12]:
def test1(a):
    if a =='s':
        return 's'
    else:
        return 'z'

In [13]:
df['col6'] = df['col5'].apply(test1)

In [14]:
df

col1  col2       col3  col4 col5  col4_4 col6
0     1    45  sudhanshu     1    s       1    s
1     2    56      kumar     4    k       4    z
2     3    67      krish     9    k       9    z
3     4    34    ineuron    16    i      16    z
4     5    34        one    25    o      25    z

In [15]:
df['col6_6'] = df['col5'].apply(lambda a : 's' if a == 's' else 'z')

In [16]:
df

col1  col2       col3  col4 col5  col4_4 col6 col6_6
0     1    45  sudhanshu     1    s       1    s      s
1     2    56      kumar     4    k       4    z      z
2     3    67      krish     9    k       9    z      z
3     4    34    ineuron    16    i      16    z      z
4     5    34        one    25    o      25    z      z

In [17]:
df['col7'] = df['col3'].apply(len)

In [18]:
df

col1  col2       col3  col4 col5  col4_4 col6 col6_6  col7
0     1    45  sudhanshu     1    s       1    s      s     9
1     2    56      kumar     4    k       4    z      z     5
2     3    67      krish     9    k       9    z      z     5
3     4    34    ineuron    16    i      16    z      z     7
4     5    34        one    25    o      25    z      z     3

In [19]:
import math

In [20]:
df['col8'] = df['col2'].apply(math.log)

In [21]:
df

col1  col2       col3  col4 col5  col4_4 col6 col6_6  col7      col8
0     1    45  sudhanshu     1    s       1    s      s     9  3.806662
1     2    56      kumar     4    k       4    z      z     5  4.025352
2     3    67      krish     9    k       9    z      z     5  4.204693
3     4    34    ineuron    16    i      16    z      z     7  3.526361
4     5    34        one    25    o      25    z      z     3  3.526361

In [22]:
import numpy as np

In [23]:
l = ["sudh" , 1,2,3,4]

In [24]:
type(l)

list

In [25]:
type(np.array(l))

numpy.ndarray

In [26]:
a1 = np.array([3,4,5,6,3.0])

In [27]:
a = np.array([[1,2] , [3,4]])

In [28]:
a

array([[1, 2],
       [3, 4]])

In [29]:
a[1][1]

4

In [30]:
a1

array([3., 4., 5., 6., 3.])

In [31]:
a1[1]

4.0

In [32]:
a2 = np.array([1,2,3,4],ndmin = 4)

In [33]:
a2

array([[[[1, 2, 3, 4]]]])

In [34]:
a2[0][0][0][0]

1

In [35]:
a

array([[1, 2],
       [3, 4]])

In [36]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [37]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [38]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [39]:
a = [1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [40]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [41]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [42]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [43]:
np.fromfunction(lambda i , j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [44]:
np.fromfunction(lambda i , j : i*j , (4,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [45]:
np.fromfunction(lambda i , j ,z ,p: i*j*z*p , (4,3,2,2),dtype = int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [46]:
a = np.fromfunction(lambda i , j ,z : i*j*z , (4,3,2),dtype = int)

In [47]:
a.reshape(2,4,-234)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4],
        [0, 0, 0],
        [3, 0, 6]]])

In [48]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [49]:
a.ndim

3

In [50]:
a.size

24

In [51]:
a.shape

(4, 3, 2)

In [52]:
a.dtype

dtype('int32')

In [53]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [54]:
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [ ]:
a = np.fromfunction(lambda i , j : i*j , (400,100),dtype = int)

In [ ]:
a

array([[    0,     0,     0, ...,     0,     0,     0],
       [    0,     1,     2, ...,    97,    98,    99],
       [    0,     2,     4, ...,   194,   196,   198],
       ...,
       [    0,   397,   794, ..., 38509, 38906, 39303],
       [    0,   398,   796, ..., 38606, 39004, 39402],
       [    0,   399,   798, ..., 38703, 39102, 39501]])

In [ ]:
pd.DataFrame(a)

0    1    2     3     4     5     6     7     8     9   ...     90  \
0     0    0    0     0     0     0     0     0     0     0  ...      0   
1     0    1    2     3     4     5     6     7     8     9  ...     90   
2     0    2    4     6     8    10    12    14    16    18  ...    180   
3     0    3    6     9    12    15    18    21    24    27  ...    270   
4     0    4    8    12    16    20    24    28    32    36  ...    360   
..   ..  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
395   0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  35550   
396   0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  35640   
397   0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  35730   
398   0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  35820   
399   0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  35910   

        91     92     93     94     95     96     97     98     99  
0        0      0      0      0      0      0      0      0      0  
1       91     92     93     94     95     96     97     98     99  
2      182    184    186    188    190    192    194    196    198  
3      273    276    279    282    285    288    291    294    297  
4      364    368    372    376    380    384    388    392    396  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
395  35945  36340  36735  37130  37525  37920  38315  38710  39105  
396  36036  36432  36828  37224  37620  38016  38412  38808  39204  
397  36127  36524  36921  37318  37715  38112  38509  38906  39303  
398  36218  36616  37014  37412  37810  38208  38606  39004  39402  
399  36309  36708  37107  37506  37905  38304  38703  39102  39501  

[400 rows x 100 columns]

In [ ]:
np.random.rand(100,4)

array([[0.85248306, 0.50369384, 0.73589494, 0.71108344],
       [0.03557535, 0.1859478 , 0.54792515, 0.29826987],
       [0.47020033, 0.09757954, 0.0085836 , 0.23671553],
       [0.177115  , 0.53807654, 0.58360737, 0.89405461],
       [0.24221316, 0.93601782, 0.87873631, 0.99968975],
       [0.49669828, 0.10051399, 0.57778719, 0.73222407],
       [0.57273056, 0.65615228, 0.85365732, 0.3043315 ],
       [0.30293881, 0.04212381, 0.35882397, 0.58153297],
       [0.48689337, 0.76949878, 0.83890621, 0.45277385],
       [0.50734949, 0.27287842, 0.71626996, 0.00446464],
       [0.74839992, 0.3543821 , 0.0870626 , 0.31672754],
       [0.2392736 , 0.17958995, 0.43395018, 0.05833227],
       [0.92283417, 0.64931207, 0.22732269, 0.40600271],
       [0.87735397, 0.7300379 , 0.92957711, 0.62558114],
       [0.9110881 , 0.49972376, 0.81965813, 0.61792837],
       [0.38391144, 0.12393006, 0.13491578, 0.29163237],
       [0.53548492, 0.79361367, 0.41141431, 0.6552665 ],
       [0.73633782, 0.18449557,

In [ ]:
np.random.randint(4,50)

32

In [ ]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0 -0.753941 -0.817731  0.497913 -0.154877  0.440541
1 -0.125808  0.277854 -0.078865  0.904879  0.011927
2  1.019199 -0.048980 -0.727625  0.619149 -0.450642
3 -0.747283  0.967514 -0.150226 -0.107359  0.323435

In [ ]:
list(range(4,10.5,2))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
a1 = np.arange(4,10.5,.2)

In [ ]:
a1

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [ ]:
a1[1:4]

array([4.2, 4.4, 4.6])

In [ ]:
arr = np.random.rand(4,5)

In [ ]:
arr

array([[0.96678281, 0.35166023, 0.93708152, 0.14640636, 0.62546993],
       [0.97404849, 0.65757559, 0.83201895, 0.84742022, 0.15049037],
       [0.78251624, 0.53726751, 0.44797833, 0.61201076, 0.49516571],
       [0.03779152, 0.15470719, 0.27272052, 0.51001873, 0.91056495]])

In [ ]:
arr[arr > .5]

array([0.96678281, 0.93708152, 0.62546993, 0.97404849, 0.65757559,
       0.83201895, 0.84742022, 0.78251624, 0.53726751, 0.61201076,
       0.51001873, 0.91056495])

In [ ]:
arr

array([[0.96678281, 0.35166023, 0.93708152, 0.14640636, 0.62546993],
       [0.97404849, 0.65757559, 0.83201895, 0.84742022, 0.15049037],
       [0.78251624, 0.53726751, 0.44797833, 0.61201076, 0.49516571],
       [0.03779152, 0.15470719, 0.27272052, 0.51001873, 0.91056495]])

In [ ]:
arr[[1,2,3] , [3,2,1]]

array([0.84742022, 0.44797833, 0.15470719])

In [56]:
arr = np.random.rand(8,5)

In [57]:
arr

array([[0.40609796, 0.12665626, 0.76652958, 0.51767646, 0.98872453],
       [0.13021369, 0.05146827, 0.27575668, 0.70368537, 0.29472785],
       [0.41336676, 0.02703933, 0.62864043, 0.9138082 , 0.77481945],
       [0.22233306, 0.00713728, 0.10837107, 0.31382084, 0.22122743],
       [0.96019693, 0.61092574, 0.65518297, 0.36593398, 0.73337177],
       [0.56305289, 0.69624037, 0.79489584, 0.74628202, 0.48523429],
       [0.62817502, 0.08762824, 0.27283126, 0.72384411, 0.99323923],
       [0.10284734, 0.61716235, 0.72505942, 0.5887093 , 0.30204991]])

In [61]:
arr[1:9 , 1:3]  # first 1:9 rows and first 1:3 columns

array([[0.05146827, 0.27575668],
       [0.02703933, 0.62864043],
       [0.00713728, 0.10837107],
       [0.61092574, 0.65518297],
       [0.69624037, 0.79489584],
       [0.08762824, 0.27283126],
       [0.61716235, 0.72505942]])

In [ ]:
a2 = arr[1:8 , [0,1,2]]

In [ ]:
a2

array([[0.83424788, 0.9772043 , 0.92511126],
       [0.02881714, 0.37262213, 0.60478181],
       [0.11836055, 0.11416884, 0.70530161],
       [0.69056392, 0.62870346, 0.79559066],
       [0.37055243, 0.9953446 , 0.41917872],
       [0.26717586, 0.52987176, 0.07728285],
       [0.57603315, 0.17999688, 0.42020654]])

In [ ]:
a2[0][0] = 100

In [ ]:
a2

array([[1.00000000e+02, 9.77204302e-01, 9.25111259e-01],
       [2.88171413e-02, 3.72622133e-01, 6.04781809e-01],
       [1.18360547e-01, 1.14168838e-01, 7.05301614e-01],
       [6.90563924e-01, 6.28703457e-01, 7.95590662e-01],
       [3.70552429e-01, 9.95344596e-01, 4.19178716e-01],
       [2.67175859e-01, 5.29871760e-01, 7.72828526e-02],
       [5.76033147e-01, 1.79996880e-01, 4.20206541e-01]])

In [ ]:
a = np.array([[1,2] ,[3,4]])
b = np.array([[2,3] , [4,5]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
b

array([[2, 3],
       [4, 5]])

In [ ]:
a*b

array([[ 2,  6],
       [12, 20]])

In [ ]:
m = a@b
# matrix multiplication formula = 
#  1st row of a * 1st column of b

In [ ]:
m

array([[10, 13],
       [22, 29]])

In [ ]:
m/0

C:\Users\nayak\AppData\Local\Temp\ipykernel_12720\3791875896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])