In [1]:
import numpy as np 

In [2]:
l = [1,2,3,4,54]

In [3]:
np.asarray(l)

array([ 1,  2,  3,  4, 54])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones((3,6,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [12]:
5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [18]:
np.empty((5,4,2))

array([[[9.61704997e-312, 9.61704563e-312],
        [6.95173306e-310, 0.00000000e+000],
        [0.00000000e+000, 9.61676710e-312],
        [9.61676710e-312, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [6.95173877e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [9.61670031e-312, 9.61676710e-312],
        [9.61676710e-312, 3.23790862e-319],
        [6.95173709e-310, 6.95173877e-310]],

       [[4.94065646e-324, 6.95173896e-310],
        [5.51718906e-313, 9.61670032e-312],
        [9.61670032e-312, 4.94065646e-324],
        [0.00000000e+000, 9.61676711e-312]],

       [[9.61676711e-312, 9.61676711e-312],
        [9.61676711e-312, 0.00000000e+000],
        [9.61676711e-312, 9.61676711e-312],
        [9.61676711e-312, 9.61676711e-312]]])

In [29]:
np.linspace(2,6,100,endpoint=False,retstep=True)

(array([2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.32, 2.36, 2.4 ,
        2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72, 2.76, 2.8 , 2.84,
        2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28,
        3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72,
        3.76, 3.8 , 3.84, 3.88, 3.92, 3.96, 4.  , 4.04, 4.08, 4.12, 4.16,
        4.2 , 4.24, 4.28, 4.32, 4.36, 4.4 , 4.44, 4.48, 4.52, 4.56, 4.6 ,
        4.64, 4.68, 4.72, 4.76, 4.8 , 4.84, 4.88, 4.92, 4.96, 5.  , 5.04,
        5.08, 5.12, 5.16, 5.2 , 5.24, 5.28, 5.32, 5.36, 5.4 , 5.44, 5.48,
        5.52, 5.56, 5.6 , 5.64, 5.68, 5.72, 5.76, 5.8 , 5.84, 5.88, 5.92,
        5.96]),
 0.04)

In [31]:
np.logspace(2,4,10,base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [32]:
np.linspace(2,4,10)

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

In [58]:
a = np.arange(4,40).reshape(6,6)

In [59]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [62]:
a.max(axis = 0)

array([34, 35, 36, 37, 38, 39])

In [63]:
a.max(axis = 1)

array([ 9, 15, 21, 27, 33, 39])

In [64]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [65]:
10+ a

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [66]:
a/0

<ipython-input-66-deacdc4ccabc>:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [67]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [71]:
a**3

array([[   64,   125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000,  9261],
       [10648, 12167, 13824, 15625, 17576, 19683],
       [21952, 24389, 27000, 29791, 32768, 35937],
       [39304, 42875, 46656, 50653, 54872, 59319]], dtype=int32)

In [70]:
pow(a,3)

array([[   64,   125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000,  9261],
       [10648, 12167, 13824, 15625, 17576, 19683],
       [21952, 24389, 27000, 29791, 32768, 35937],
       [39304, 42875, 46656, 50653, 54872, 59319]], dtype=int32)

In [88]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [89]:
b = np.array([2,3,1,2,3,4])

In [93]:
a+b

array([[ 6,  8,  7,  9, 11, 13],
       [12, 14, 13, 15, 17, 19],
       [18, 20, 19, 21, 23, 25],
       [24, 26, 25, 27, 29, 31],
       [30, 32, 31, 33, 35, 37],
       [36, 38, 37, 39, 41, 43]])

In [104]:
b = b.reshape(-1664566,1)
 b.reshape(6,1)
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [105]:
b.T +a

array([[ 6,  8,  7,  9, 11, 13],
       [12, 14, 13, 15, 17, 19],
       [18, 20, 19, 21, 23, 25],
       [24, 26, 25, 27, 29, 31],
       [30, 32, 31, 33, 35, 37],
       [36, 38, 37, 39, 41, 43]])

In [102]:
 b.T

array([[2],
       [3],
       [1],
       [2],
       [3],
       [4]])

In [95]:
a+b

array([[ 6,  8,  7,  9, 11, 13],
       [12, 14, 13, 15, 17, 19],
       [18, 20, 19, 21, 23, 25],
       [24, 26, 25, 27, 29, 31],
       [30, 32, 31, 33, 35, 37],
       [36, 38, 37, 39, 41, 43]])

In [78]:
a + 10

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [106]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [107]:
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [108]:
np.exp(a)

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

In [109]:
np.log10(a)

array([[0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
        0.95424251],
       [1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
        1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
        1.32221929],
       [1.34242268, 1.36172784, 1.38021124, 1.39794001, 1.41497335,
        1.43136376],
       [1.44715803, 1.462398  , 1.47712125, 1.49136169, 1.50514998,
        1.51851394],
       [1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
        1.59106461]])

In [110]:
x = np.array([1,2,3])

In [111]:
y = x

In [112]:
y

array([1, 2, 3])

In [113]:
z = np.copy(x)

In [114]:
z

array([1, 2, 3])

In [115]:
x[0] = 100

In [116]:
y

array([100,   2,   3])

In [117]:
z

array([1, 2, 3])

In [118]:
id(z)

1946571721504

In [119]:
id(x)

1946571749056

In [120]:
id(y)

1946571749056

In [121]:
x

array([100,   2,   3])

In [122]:
id(x[0])

1946558984464

In [123]:
y

array([100,   2,   3])

In [124]:
id(y[0])

1946558985072

In [125]:
id(x[1])

1946558985456

In [126]:
id(y[1])

1946558985616

In [127]:
id(z[1])

1946573532144

In [128]:
x = np.array([1,2,3])

In [130]:
y = x

In [131]:
id(x)

1946572387072

In [132]:
id(y)

1946572387072

In [133]:
id(x[0])

1946573532112

In [134]:
id(y[0])

1946573531920

In [3]:
import numpy as np

In [4]:
su = np.array([567,345])

In [5]:
df = su

In [6]:
id(su)

2443147618464

In [7]:
id(df)

2443147618464

In [8]:
id(su[0])

2443151609680

In [9]:
id(df[0])

2443146878384

In [10]:
id(su[1])

2443146878064

In [11]:
id(df[1])

2443151609456

In [17]:
id(su[1]) == id(df[0])

True

In [16]:
id(su) == id(df)

True

In [18]:
xt = np.array([34,67,89])

In [19]:
id(xt[0]) == id(su[0])

True

In [20]:
c = "sudh"

In [21]:
id(c) == id(su[0])

False